#### PyTorch Release Status (배포 상태)

```python
😮
Stable : 장기적인 확인을 거쳐 일반적인 사용에 문제가 없고 이전 버전과 호환도 유지되는 것으로 판단된 기능.
Beta : 아직 확인 중인 기능. Stable에 비해 전반 적용에 대한 안정성 확보가 덜 되었고, 이에 따른 개선이 필요할 수도 있음.
Prototype : 피드백과 배포를 위한 초기 단계에 있는 기능.
```


##### PyTorch의 Linear Algebra

``` python
torch.linalg
```

##### PyTorch의 Matrix Multiplication

``` python
torch.matmul()
```

##### PyTorch의 Norm

``` python
torch.linalg.vector_norm()
torch.linalg.matrix_norm()
```

##### PyTorch의 기본 구성 요소 Tensor

``` python
torch.tensor : 데이터를 Tensor 객체로 만들어주는 함수.
torch.Tensor : 하나의 데이터 타입을 가지는 다차원 행렬.
```

##### Add

In [1]:
import torch

A = torch.Tensor([5])
B = torch.Tensor([7])

torch.add(A, B)

tensor([12.])

In [2]:
A + B

tensor([12.])

In [3]:
# 피연산자 중 하나라도 tensor가 입력되면 출력값은 tensor.
A + 7

tensor([12.])

- `+` : torch.add
- `-` : torch.sub
- `*` : torch.mul
- `/` : torch.div

##### 사칙연산

In [4]:
A = torch.Tensor([3])
B = torch.Tensor([7])
C = torch.Tensor([2])
D = torch.Tensor([5])
E = torch.Tensor([10])

# (3 + 7) * 2 - 5 / 10
output = torch.add(A, B)
output = torch.mul(output, C)
temp = torch.div(D, E)
output = torch.sub(output, temp)

if output == 19.5:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


##### 인덱싱 (Indexing)

In [5]:
A = torch.Tensor([[1, 2],
                  [3, 4]])

# get [1, 3] using torch.index_select
output = A
indices = torch.tensor([0])
output = torch.index_select(output, 1, indices)
output = output.view(1, -1)

if torch.all(output == torch.Tensor([1, 3])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [6]:
A = torch.Tensor([[1, 2],
                  [3, 4]])

# get [1, 3] like python indexing
output = A
output = output[:, 0]

if torch.all(output == torch.Tensor([1, 3])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


##### 2D tensor에서 대각선 요소 가져오기 - 2D gather

In [9]:
A = torch.Tensor([[1, 2],
                  [3, 4]])

# torch.gather
indices = torch.tensor([[0],[1]])
output = torch.gather(A, 1, indices)
output = output.view(1, -1)

if torch.all(output == torch.Tensor([1, 4])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


##### 3D tensor에서 대각선 요소 가져오기 - 3D gather

In [10]:
A = torch.Tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])

# torch.gather
output = A
indices = torch.tensor([[[0],[1]], [[0], [1]]])
output = torch.gather(A, 2, indices).squeeze()

if torch.all(output == torch.Tensor([[1, 4], [5, 8]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


##### 임의의 크기의 3D tensor에서 대각선 요소 가져오기 - 3D gather

In [11]:
# 임의 크기의 3D tensor에서 대각선 요소 가져와 2D로 반환
def get_diag_element_3D(A):
    output = A
    C, H, W = output.shape[0], output.shape[1], output.shape[2]
    indices = torch.tensor([i for i in range(min(H,W))]).expand(C,-1).unsqueeze(-1)
    output = torch.gather(A, len(A.size()) - 1, indices).squeeze()
    return output

# 임의 크기 3D tensor
C = 1
H = 2
W = 3

A = torch.tensor([i for i in range(1, C*H*W + 1)])
A = A.view(C, H, W)

print(f"원본 3D 행렬\n{A}")
print("-" * 50)

print(f"대각선 요소를 모은 2D 행렬")
get_diag_element_3D(A)

원본 3D 행렬
tensor([[[1, 2, 3],
         [4, 5, 6]]])
--------------------------------------------------
대각선 요소를 모은 2D 행렬


tensor([1, 5])

In [12]:
A = torch.tensor([[[1]]])

if torch.all(get_diag_element_3D(A) == torch.Tensor([[1]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [13]:
A = torch.Tensor([[[1, 2],
                   [3, 4]],
                  [[5, 6],
                   [7, 8]]])

if torch.all(get_diag_element_3D(A) == torch.Tensor([[1, 4],
                                                     [5, 8]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [14]:
A = torch.Tensor([[[1, 2, 3],
                   [4, 5, 6]]])

if torch.all(get_diag_element_3D(A) == torch.Tensor([[1, 5]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [15]:
A = torch.tensor([[[ 1,  2,  3,  4,  5],
                   [ 6,  7,  8,  9, 10],
                   [11, 12, 13, 14, 15]],
          
                  [[16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25],
                   [26, 27, 28, 29, 30]]])

if torch.all(get_diag_element_3D(A) == torch.Tensor([[ 1,  7, 13],
                                                     [16, 22, 28]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [16]:
A = torch.tensor([[[ 1,  2,  3],
                   [ 4,  5,  6],
                   [ 7,  8,  9],
                   [10, 11, 12],
                   [13, 14, 15]],
        
                  [[16, 17, 18],
                   [19, 20, 21],
                   [22, 23, 24],
                   [25, 26, 27],
                   [28, 29, 30]],
        
                  [[31, 32, 33],
                   [34, 35, 36],
                   [37, 38, 39],
                   [40, 41, 42],
                   [43, 44, 45]]])

if torch.all(get_diag_element_3D(A) == torch.Tensor([[ 1,  5,  9],
                                                     [16, 20, 24],
                                                     [31, 35, 39]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


##### PyTorch 공식 문서 훑기 & 함수 사용 예제

In [17]:
import torch
import numpy as np

# 🦆 torch.from_numpy
a = np.array([1,2,3])
t = torch.from_numpy(a)

In [18]:
# 🦆 torch.zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [19]:
# 🦆 torch.zeros_like
torch.zeros_like(t)

tensor([0, 0, 0])

In [20]:
# 🦆 torch.chunk
t = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print(torch.chunk(t, 2, 0))
print(torch.chunk(t, 2, 1))

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]))
(tensor([[1, 2],
        [4, 5]]), tensor([[3],
        [6]]))


In [21]:
# 🦆 torch.swapdims
x = torch.tensor([[[0,1],[2,3]],[[4,5],[6,7]]])
torch.swapdims(x, 0, 1)

tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])

In [24]:
# 🦆 torch.Tensor.scatter_
src =torch.arange(1, 11).reshape((2, 5))
index = torch.tensor([[0, 1, 2, 0]])
torch.zeros(3, 5, dtype=src.dtype).scatter_(0, index, src)

tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [25]:
# 🦆 Random sampling
import torch
seed = torch.seed()
print(seed)
manual_seed = torch.manual_seed(seed)
print(manual_seed)
initial_seed = torch.initial_seed()
print(initial_seed)

1333914475654494612
1333914475654494612


In [26]:
# 🦆 Math operations - Pointwise Ops
temp = a = torch.randn(4)
print(temp)
temp_abs = torch.abs(temp)
print(temp_abs)
temp_acos = torch.acos(temp)
print(temp_acos)
temp_acosh = torch.acosh(temp)
print(temp_acosh)

tensor([0.9554, 0.9896, 1.9759, 0.0125])
tensor([0.9554, 0.9896, 1.9759, 0.0125])
tensor([0.2997, 0.1447,    nan, 1.5583])
tensor([   nan,    nan, 1.3029,    nan])


In [27]:
# 🦆 Math operations - Reduction Ops
temp = a = torch.randn(4)
print(temp)
temp_argmax = torch.argmax(temp)
print(temp_argmax)
temp_argmin = torch.argmin(temp)
print(temp_argmin)
temp_all = torch.all(temp)
print(temp_all)

tensor([ 0.4124, -1.0585,  0.0942, -0.5091])
tensor(0)
tensor(1)
tensor(True)


In [28]:
# 🦆 Math operations - Comparison Ops
temp = a = torch.randn(4)
print(temp)
temp_allclose = torch.allclose(temp, temp)
print(temp_allclose)
temp_argsort = torch.argsort(temp)
print(temp_argsort)
temp_eq = torch.eq(temp, temp)
print(temp_eq)

tensor([ 1.0435, -0.9395,  2.9141,  1.0029])
True
tensor([1, 3, 0, 2])
tensor([True, True, True, True])


In [ ]:
# 🦆 Math operations - Other Operations

In [29]:
#### einsum

# trace
torch.einsum('ii', torch.randn(4, 4))

tensor(-0.8364)

In [30]:
# diagonal
torch.einsum('ii->i', torch.randn(4, 4))

tensor([-0.7342,  0.2111,  0.1528, -0.3827])

In [31]:
# outer product
x = torch.randn(5)
y = torch.randn(4)
torch.einsum('i,j->ij', x, y)

tensor([[ 0.6560,  0.6210, -0.3489, -0.6460],
        [ 0.4080,  0.3863, -0.2170, -0.4018],
        [ 0.0282,  0.0267, -0.0150, -0.0278],
        [-0.3338, -0.3160,  0.1775,  0.3287],
        [ 1.0032,  0.9498, -0.5335, -0.9880]])

In [32]:
# batch matrix multiplication
As = torch.randn(3,2,5)
Bs = torch.randn(3,5,4)
torch.einsum('bij,bjk->bik', As, Bs)

tensor([[[-2.5163, -1.0991,  4.3671,  0.7771],
         [-0.4865, -0.7334,  2.5397,  1.3406]],

        [[ 2.0850,  0.5988,  2.4922,  2.7068],
         [-1.0223,  1.0416,  0.3803, -1.3615]],

        [[ 0.1737,  0.3008,  0.1883,  0.7262],
         [-1.5035, -2.5971,  0.5111, -1.6418]]])

In [33]:
# batch permute
A = torch.randn(2, 3, 4, 5)
torch.einsum('...ij->...ji', A).shape

torch.Size([2, 3, 5, 4])

In [34]:
# equivalent to torch.nn.functional.bilinear
A = torch.randn(3,5,4)
l = torch.randn(2,5)
r = torch.randn(2,4)
torch.einsum('bn,anm,bm->ba', l, A, r)

tensor([[ 0.4313,  0.3073,  1.1945],
        [ 8.5409, -2.6836, -2.5755]])

In [35]:
#### atleast_1d

x = torch.randn(2)
print(x)

tensor([ 1.3830, -0.0910])


In [36]:
torch.atleast_1d(x)

tensor([ 1.3830, -0.0910])

In [37]:
x = torch.tensor(1.)
torch.atleast_1d(x)

tensor([1.])

In [38]:
x = torch.tensor(0.5)
y = torch.tensor(1.)
torch.atleast_1d((x,y))

(tensor([0.5000]), tensor([1.]))

In [39]:
#### bucketize

boundaries = torch.tensor([1, 3, 5, 7, 9])
print(boundaries)

tensor([1, 3, 5, 7, 9])


In [40]:
v = torch.tensor([[3, 6, 9], [3, 6, 9]])
torch.bucketize(v, boundaries)

tensor([[1, 3, 4],
        [1, 3, 4]])

In [41]:
torch.bucketize(v, boundaries, right=True)

tensor([[2, 3, 5],
        [2, 3, 5]])

In [ ]:
# 🦆 Math operations - BLAS and LAPACK Operations

In [42]:
M = torch.randn(2, 3)
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.addmm(M, mat1, mat2)

tensor([[ 0.6278, -0.6869, -0.3568],
        [ 0.5679, -0.8697, -0.4615]])

In [43]:
a = torch.eye(10)
torch.matrix_rank(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.matrix_rank is deprecated in favor of torch.linalg.matrix_rankand will be removed in a future PyTorch release. The parameter 'symmetric' was renamed in torch.linalg.matrix_rank to 'hermitian'. (Triggered internally at  /pytorch/aten/src/ATen/native/LinearAlgebra.cpp:438.)
  


tensor(10)

In [44]:
b = torch.eye(10)
b[0, 0] = 0
torch.matrix_rank(b)

tensor(9)

In [45]:
a = torch.tensor([[12., -51, 4],
                  [6, 167, -68],
                  [-4, 24, -41]])
q, r = torch.qr(a)
torch.mm(q, r).round()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: UserWarning: torch.qr is deprecated in favor of torch.linalg.qr and will be removed in a future PyTorch release.
The boolean parameter 'some' has been replaced with a string parameter 'mode'.
Q, R = torch.qr(A, some)
should be replaced with
Q, R = torch.linalg.qr(A, 'reduced' if some else 'complete') (Triggered internally at  /pytorch/aten/src/ATen/native/BatchLinearAlgebra.cpp:1940.)
  after removing the cwd from sys.path.


tensor([[ 12., -51.,   4.],
        [  6., 167., -68.],
        [ -4.,  24., -41.]])

In [46]:
torch.allclose(torch.matmul(q, r), a)

True

In [47]:
#### addmv

M = torch.randn(2)
mat = torch.randn(2, 3)
vec = torch.randn(3)
torch.addmv(M, mat, vec)

tensor([ 2.5329, -1.5686])

In [48]:
#### baddbmm

M = torch.randn(10, 3, 5)
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
torch.baddbmm(M, batch1, batch2).size()

torch.Size([10, 3, 5])

##### torch.nn Linear Layers

In [52]:
from torch import nn
X = torch.Tensor([[1, 2],
                  [3, 4]])
# 크기 변환 
X = torch.nn.Linear(2,5)

X = torch.Tensor([[1, 2],
                  [3, 4]])

# Identity
temp = nn.Identity(X)
print(temp(X).size())

torch.Size([2, 2])


```python
😮
Linear : 데이터를 선형 변환
LazyLinear : 첫 번째 호출이 완료된 후 초기화되고 Linear 적용.
```


##### nn.Module 모델 제작

In [53]:
# Add with nn.Module

import torch
from torch import nn

class Add(nn.Module):
    def __init__(self):
        super(Add, self).__init__()

    def forward(self, x1, x2):
        return x1 + x2

x1 = torch.tensor([1])
x2 = torch.tensor([2])

add = Add()
output = add(x1, x2)
print(output)

if output == 3:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

tensor([3])
🎉🎉🎉 성공!!! 🎉🎉🎉


In [54]:
# torch.nn.Sequential로 모듈 묶기 (순차 실행)

import torch
from torch import nn

class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

calculator = nn.Sequential(
    Add(3),
    Add(2),
    Add(5)
)

x = torch.tensor([1])

output = calculator(x)

if output == 11:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [55]:
# torch.nn.ModuleList로 모듈 묶기 (not 순차 실행. pikking.)

import torch
from torch import nn

class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

class Calculator(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_list = nn.ModuleList([Add(2), Add(3), Add(5)])

    def forward(self, x):
        # y = ((x + 3) + 2) + 5
        for i, add in enumerate(self.add_list):
            x = x+add(0)
        return x

x = torch.tensor([1])

calculator = Calculator()
output = calculator(x)

if output == 11:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [56]:
# torch.nn.ModuleDict로 모듈 묶기

import torch
from torch import nn

class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

class Calculator(nn.Module):
    def __init__(self):
        super().__init__()
        self.add_dict = nn.ModuleDict({'add2': Add(2),
                                       'add3': Add(3),
                                       'add5': Add(5)})

    def forward(self, x):
        # y = ((x + 3) + 2) + 5
        for key in self.add_dict.keys():
            x += self.add_dict[key](0)
        return x

x = torch.tensor([1])

calculator = Calculator()
output = calculator(x)

if output == 11:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [57]:
# Python List vs PyTorch ModuleList

class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value


class PythonList(nn.Module):
    """Python List"""
    def __init__(self):
        super().__init__()

        # Python List
        self.add_list = [Add(2), Add(3), Add(5)]

    def forward(self, x):
        x = self.add_list[1](x)
        x = self.add_list[0](x)
        x = self.add_list[2](x)
        
        return x

class PyTorchList(nn.Module):
    """PyTorch List"""
    def __init__(self):
        super().__init__()

        # Pytorch ModuleList
        self.add_list = nn.ModuleList([Add(2), Add(3), Add(5)])

    def forward(self, x):
        x = self.add_list[1](x)
        x = self.add_list[0](x)
        x = self.add_list[2](x)
        
        return x

x = torch.tensor([1])

python_list = PythonList()
pytorch_list = PyTorchList()

print(python_list(x), pytorch_list(x))

tensor([11]) tensor([11])


In [58]:
# Python List로 모아놓은 모듈들은 사라졌다.
python_list

PythonList()

In [59]:
# 반면 PyTorch로 모아놓은 모듈들은 남아있다.
pytorch_list

PyTorchList(
  (add_list): ModuleList(
    (0): Add()
    (1): Add()
    (2): Add()
  )
)

```python
😮
Model은 nn.Module을 상속하여 정의.
단순 list로 저장 시, 레이어 인식이 안될 수 있음.
```


In [60]:
# using condition statement

import torch
from torch import nn

class Add(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x + self.value

class Sub(nn.Module):
    def __init__(self, value):
        super().__init__()
        self.value = value

    def forward(self, x):
        return x - self.value

class Calculator(nn.Module):
    def __init__(self, cal_type):
        super().__init__()
        self.cal_type = cal_type
        self.add = Add(3)
        self.sub = Sub(3)

    def forward(self, x):
        # "add" -> y = x + 3
        # "sub" -> y = x - 3
        # "add", "sub"가 아닌 다른 문자열이 입력되면 ValueError
        if self.cal_type == "add":
            x = self.add(x)
        elif self.cal_type == "sub":
            x = self.sub(x)
        else:
            raise ValueError

        return x

x = torch.tensor([5])

try:
    calculator = Calculator("none")
    output = calculator(x)

    print("🦆 잘못된 문자열 입력에는 에러를 발생시키세요!!")
except ValueError:
    calculator = Calculator("add")
    add_output = calculator(x)

    calculator = Calculator("sub")
    sub_output = calculator(x)
    
    if add_output == 8 and sub_output == 2:
        print("🎉🎉🎉 성공!!! 🎉🎉🎉")
    else:
        print("🦆 다시 도전해봐요!")
except:
    print("🦆 ValueError를 발생시키세요!!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [61]:
# 모듈의 흐름을 느껴봐

import torch
from torch import nn


# Function
class Function_A(nn.Module):
    def __init__(self):
        super().__init__()
        print(f"        Function A Initialized")

    def forward(self, x):
        print(f"        Function A started")
        print(f"        Function A done")

class Function_B(nn.Module):
    def __init__(self):
        super().__init__()
        print(f"        Function B Initialized")

    def forward(self, x):
        print(f"        Function B started")
        print(f"        Function B done")

class Function_C(nn.Module):
    def __init__(self):
        super().__init__()
        print(f"        Function C Initialized")

    def forward(self, x):
        print(f"        Function C started")
        print(f"        Function C done")

class Function_D(nn.Module):
    def __init__(self):
        super().__init__()
        print(f"        Function D Initialized")

    def forward(self, x):
        print(f"        Function D started")
        print(f"        Function D done")


# Layer
class Layer_AB(nn.Module):
    def __init__(self):
        super().__init__()

        self.a = Function_A()
        self.b = Function_B()

        print(f"    Layer AB Initialized")

    def forward(self, x):
        print(f"    Layer AB started")
        self.a(x)
        self.b(x)
        print(f"    Layer AB done")

class Layer_CD(nn.Module):
    def __init__(self):
        super().__init__()

        self.c = Function_C()
        self.d = Function_D()

        print(f"    Layer CD Initialized")

    def forward(self, x):
        print(f"    Layer CD started")
        self.c(x)
        self.d(x)
        print(f"    Layer CD done")


# Model
class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.ab = Layer_AB()
        self.cd = Layer_CD()

        print(f"Model ABCD Initialized\n")

    def forward(self, x):
        print(f"Model ABCD started")
        self.ab(x)
        self.cd(x)
        print(f"Model ABCD done\n")


x = torch.tensor([7])

model = Model()
model(x)

print("🎉🎉🎉 모든 딥러닝 모델은 이처럼 Module들이 쌓이고 쌓여서 만들어집니다! 🎉🎉🎉")
print("🎉🎉🎉 흐름을 느껴보시고 이 흐름이 이해가 되신 분은 다음으로 가시면 됩니다! 🎉🎉")

        Function A Initialized
        Function B Initialized
    Layer AB Initialized
        Function C Initialized
        Function D Initialized
    Layer CD Initialized
Model ABCD Initialized

Model ABCD started
    Layer AB started
        Function A started
        Function A done
        Function B started
        Function B done
    Layer AB done
    Layer CD started
        Function C started
        Function C done
        Function D started
        Function D done
    Layer CD done
Model ABCD done

🎉🎉🎉 모든 딥러닝 모델은 이처럼 Module들이 쌓이고 쌓여서 만들어집니다! 🎉🎉🎉
🎉🎉🎉 흐름을 느껴보시고 이 흐름이 이해가 되신 분은 다음으로 가시면 됩니다! 🎉🎉


In [62]:
# Parameter
# Tensor 이용시와 달리 Parameter Class를 이용해 생성시,
# output tensor에 gradient function이 추가.

import torch
from torch import nn
from torch.nn.parameter import Parameter

class Linear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.W = Parameter(torch.ones((out_features, in_features)))
        self.b =Parameter(torch.ones(out_features))

    def forward(self, x):
        output = torch.addmm(self.b, x, self.W.T)
        return output

x = torch.Tensor([[1, 2],
                  [3, 4]])

linear = Linear(2, 3)
output = linear(x)

if torch.all(output == torch.Tensor([[4, 4, 4],
                                     [8, 8, 8]])):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [63]:
# buffer

import torch
from torch import nn
from torch.nn.parameter import Parameter

class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.parameter = Parameter(torch.Tensor([7]))
        self.tensor = torch.Tensor([7])
        self.register_buffer('buffer', torch.Tensor([7]))

model = Model()

try:
    buffer = model.get_buffer('buffer')
    if buffer == 7:
        print("🎉🎉🎉 성공!!! 🎉🎉🎉\n")
        print("🎉 이제 buffer에 등록된 tensor는 모델이 저장될 때 같이 저장될거예요! 🎉")
        print(model.state_dict())
    else:
        print("🦆 다시 도전해봐요!")
except:
    print("🦆 다시 도전해봐요!")


🎉🎉🎉 성공!!! 🎉🎉🎉

🎉 이제 buffer에 등록된 tensor는 모델이 저장될 때 같이 저장될거예요! 🎉
OrderedDict([('parameter', tensor([7.])), ('buffer', tensor([7.]))])


```python
😮
- "Tensor"
    - ❌ gradient 계산
    - ❌ 값 업데이트
    - ❌ 모델 저장시 값 저장
- "Parameter"
    - ✅ gradient 계산
    - ✅ 값 업데이트
    - ✅ 모델 저장시 값 저장
- "Buffer"
    - ❌ gradient 계산
    - ❌ 값 업데이트
    - ✅ 모델 저장시 값 저장
```


##### nn.Module 분석

In [64]:
# 자신에게 속한 모든 submodule을 표시
for name, module in model.named_modules():
    print(f"[ Name ] : {name}\n[ Module ]\n{module}")
    print("-" * 30)

[ Name ] : 
[ Module ]
Model()
------------------------------


In [65]:
# 한 단계 아래의 submodule만 표시
for name, child in model.named_children():
    print(f"[ Name ] : {name}\n[ Children ]\n{child}")
    print("-" * 30)

In [66]:
# 파라미터 목록 표시
for name, parameter in model.named_parameters():
    print(f"[ Name ] : {name}\n[ Parameter ]\n{parameter}")
    print("-" * 30)

[ Name ] : parameter
[ Parameter ]
Parameter containing:
tensor([7.], requires_grad=True)
------------------------------


In [67]:
# buffer 표시
for name, buffer in model.named_buffers():
    print(f"[ Name ] : {name}\n[ Buffer ] : {buffer}")
    print("-" * 30)

[ Name ] : buffer
[ Buffer ] : tensor([7.])
------------------------------


In [68]:
# 부덕 모델

import torch
from torch import nn
from torch.nn.parameter import Parameter


# 아래 코드는 수정하실 필요가 없습니다!
# 하지만 아래 과제를 진행하기 전에 아래 코드를 보면서 최대한 이해해보세요!

# Function
class Function_A(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name

    def forward(self, x):
        x = x * 2
        return x

class Function_B(nn.Module):
    def __init__(self):
        super().__init__()
        self.W1 = Parameter(torch.Tensor([10]))
        self.W2 = Parameter(torch.Tensor([2]))

    def forward(self, x):
        x = x / self.W1
        x = x / self.W2

        return x

class Function_C(nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer('duck', torch.Tensor([7]), persistent=True)

    def forward(self, x):
        x = x * self.duck
        
        return x

class Function_D(nn.Module):
    def __init__(self):
        super().__init__()
        self.W1 = Parameter(torch.Tensor([3]))
        self.W2 = Parameter(torch.Tensor([5]))
        self.c = Function_C()

    def forward(self, x):
        x = x + self.W1
        x = self.c(x)
        x = x / self.W2

        return x


# Layer
class Layer_AB(nn.Module):
    def __init__(self):
        super().__init__()

        self.a = Function_A('duck')
        self.b = Function_B()

    def forward(self, x):
        x = self.a(x) / 5
        x = self.b(x)

        return x

class Layer_CD(nn.Module):
    def __init__(self):
        super().__init__()

        self.c = Function_C()
        self.d = Function_D()

    def forward(self, x):
        x = self.c(x)
        x = self.d(x) + 1

        return x


# Model
class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.ab = Layer_AB()
        self.cd = Layer_CD()

    def forward(self, x):
        x = self.ab(x)
        x = self.cd(x)

        return x

x = torch.tensor([7])

model = Model()
model(x)

tensor([6.5720], grad_fn=<AddBackward0>)

In [69]:
# In Function_D, Function_C 참조 제거

class Function_D(nn.Module):
    def __init__(self):
        super().__init__()
        self.W1 = Parameter(torch.Tensor([3]))
        self.W2 = Parameter(torch.Tensor([5]))
        # self.c = Function_C()
        self.register_buffer('modify_c', torch.Tensor([7]), persistent = True)

    def forward(self, x):
        x = x + self.W1
        # x = self.c(x)
        x *= self.modify_c
        x = x / self.W2

        return x

In [70]:
# In Function_A, 출력 수정

class Function_A(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name

    def forward(self, x):
        x = x * 2
        return x

    def extra_repr(self) :
        return f'name={self.name}'

##### nn.Module hook & apply

In [71]:
# What is hook?

def program_A(x):
    print('program A processing!')
    return x + 3

def program_B(x):
    print('program B processing!')
    return x - 3

class Package(object):
    """프로그램 A와 B를 묶어놓은 패키지 코드"""
    def __init__(self):
        self.programs = [program_A, program_B]
        self.hooks = []

    def __call__(self, x):
        for program in self.programs:
            x = program(x)

            # Package를 사용하는 사람이 자신만의 custom program을
            # 등록할 수 있도록 미리 만들어놓은 인터페이스 hook
            if self.hooks:
                for hook in self.hooks:
                    output = hook(x)

                    # return 값이 있는 hook의 경우에만 x를 업데이트 한다
                    if output:
                        x = output

        return x

# 패키지 생성
package = Package()

# 패키지 실행
input = 3
output = package(input)

# 패키지 결과
print(f"Package Process Result! [ input {input} ] [ output {output} ]")

program A processing!
program B processing!
Package Process Result! [ input 3 ] [ output 3 ]


In [72]:
# forward hook 전파 과정

import torch
from torch import nn

class Add(nn.Module):
    def __init__(self):
        super().__init__() 

    def forward(self, x1, x2):
        output = torch.add(x1, x2)

        return output

add = Add()

answer = []

def pre_hook(module, input):
    x1, x2 = input
    answer.append(x1)
    answer.append(x2)
add.register_forward_pre_hook(pre_hook)

def hook(module, input, output):
    answer.append(output)
add.register_forward_hook(hook)

x1 = torch.rand(1)
x2 = torch.rand(1)

output = add(x1, x2)

if answer == [x1, x2, output]:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [73]:
# 전파중 값 수정 가능

def hook(module, input, output):
    output += 5
    return output
add.register_forward_hook(hook)

In [74]:
# backward hook
# forward hook은 module에만 적용할 수 있으나,
# backward hook은 tensor, module 모두 적용 가능

import torch
from torch import nn
from torch.nn.parameter import Parameter

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.W = Parameter(torch.Tensor([5]))

    def forward(self, x1, x2):
        output = x1 * x2
        output = output * self.W

        return output

model = Model()

answer = []

def module_hook(module, grad_input, grad_output):
    answer.append(x2 * grad_input[0])
    answer.append(x1 * grad_input[0])
    answer.append(grad_output[0])
model.register_backward_hook(module_hook)

x1 = torch.rand(1, requires_grad=True)
x2 = torch.rand(1, requires_grad=True)

output = model(x1, x2)
output.retain_grad()
output.backward()

if answer == [x1.grad, x2.grad, output.grad]:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:974: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "


In [75]:
# tensor 단위 backward hook

import torch
from torch import nn
from torch.nn.parameter import Parameter

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.W = Parameter(torch.Tensor([5]))

    def forward(self, x1, x2):
        output = x1 * x2
        output = output * self.W

        return output

model = Model()

answer = []

def tensor_hook(grad):
    answer.append(grad)
list(model.parameters())[0].register_hook(tensor_hook)

x1 = torch.rand(1, requires_grad=True)
x2 = torch.rand(1, requires_grad=True)

output = model(x1, x2)
output.backward()

if answer == [model.W.grad]:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [76]:
# 마찬가지로 전파 값 수정 가능

import torch
from torch import nn
from torch.nn.parameter import Parameter

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.W = Parameter(torch.Tensor([5]))

    def forward(self, x1, x2):
        output = x1 * x2
        output = output * self.W

        return output

model = Model()

def module_hook(module, grad_input, grad_output):
    grad_input = list(grad_input)
    grad_input[0] = 1/(x1+x2)
    return tuple(grad_input)
model.register_backward_hook(module_hook)

x1 = torch.rand(1, requires_grad=True)
x2 = torch.rand(1, requires_grad=True)

output = model(x1, x2)
output.backward()

if x1.grad + x2.grad == 1:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py:974: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "


In [77]:
# apply example

import torch
from torch import nn

@torch.no_grad()
def init_weights(m):
    print(m)
    if type(m) == nn.Linear:
        m.weight.fill_(1.0)
        print(m.weight)

net = nn.Sequential(nn.Linear(2, 2), nn.Linear(2, 2))
net.apply(init_weights)

Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Linear(in_features=2, out_features=2, bias=True)
Parameter containing:
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)


Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
)

In [78]:
# 수정을 위한 부덕 모델

import torch
from torch import nn
from torch.nn.parameter import Parameter


# 아래 코드는 수정하실 필요가 없습니다!
# 하지만 아래 과제를 진행하기 전에 아래 코드를 보면서 최대한 이해해보세요!

# Function
class Function_A(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.W = Parameter(torch.rand(1))

    def forward(self, x):
        return x + self.W

class Function_B(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.W = Parameter(torch.rand(1))

    def forward(self, x):
        return x - self.W

class Function_C(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.W = Parameter(torch.rand(1))

    def forward(self, x):
        return x * self.W

class Function_D(nn.Module):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.W = Parameter(torch.rand(1))

    def forward(self, x):
        return x / self.W


# Layer
class Layer_AB(nn.Module):
    def __init__(self):
        super().__init__()

        self.a = Function_A('plus')
        self.b = Function_B('substract')

    def forward(self, x):
        x = self.a(x)
        x = self.b(x)

        return x

class Layer_CD(nn.Module):
    def __init__(self):
        super().__init__()

        self.c = Function_C('multiply')
        self.d = Function_D('divide')

    def forward(self, x):
        x = self.c(x)
        x = self.d(x)

        return x


# Model
class Model(nn.Module):
    def __init__(self):
        super().__init__()

        self.ab = Layer_AB()
        self.cd = Layer_CD()

    def forward(self, x):
        x = self.ab(x)
        x = self.cd(x)

        return x


model = Model()

def print_module(module):
    print(module)
    print("-" * 30)

returned_module = model.apply(print_module)

Function_A()
------------------------------
Function_B()
------------------------------
Layer_AB(
  (a): Function_A()
  (b): Function_B()
)
------------------------------
Function_C()
------------------------------
Function_D()
------------------------------
Layer_CD(
  (c): Function_C()
  (d): Function_D()
)
------------------------------
Model(
  (ab): Layer_AB(
    (a): Function_A()
    (b): Function_B()
  )
  (cd): Layer_CD(
    (c): Function_C()
    (d): Function_D()
  )
)
------------------------------


In [79]:
# 가중치 초기화 (Weight Initialization)

def weight_initialization(module):
    module_name = module.__class__.__name__
    if module_name.find('Function') != -1 :
        module.W.data.fill_(1.0)
returned_module = model.apply(weight_initialization)

x = torch.rand(1)

output = model(x)

if torch.isclose(output, x):
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
else:
    print("🦆 다시 도전해봐요!")

🎉🎉🎉 성공!!! 🎉🎉🎉


In [80]:
# apply - repr 수정

model = Model()

from functools import partial

def function_repr(self):
    return f'name={self.name}'

def add_repr(module):
    module_name = module.__class__.__name__
    if module_name.find('Function') != -1:
        module.extra_repr = partial(function_repr, module)
returned_module = model.apply(add_repr)

model_repr = repr(model)

print("모델 출력 결과")
print("-" * 30)
print(model_repr)
print("-" * 30)

answer = "Model(\n  (ab): Layer_AB(\n    (a): Function_A(name=plus)\n    (b): Function_B(name=substract)\n  )\n  (cd): Layer_CD(\n    (c): Function_C(name=multiply)\n    (d): Function_D(name=divide)\n  )\n)"

if model_repr == answer:
    print("🎉🎉🎉 성공!!! 🎉🎉🎉")
    print("🦆 너무 고마워요 꽉꽉!")
else:
    print("🦆 다시 도전해봐요!")


모델 출력 결과
------------------------------
Model(
  (ab): Layer_AB(
    (a): Function_A(name=plus)
    (b): Function_B(name=substract)
  )
  (cd): Layer_CD(
    (c): Function_C(name=multiply)
    (d): Function_D(name=divide)
  )
)
------------------------------
🎉🎉🎉 성공!!! 🎉🎉🎉
🦆 너무 고마워요 꽉꽉!


In [81]:
# apply - Function 수정

model = Model()

def add_bias(module):
    module_name = module.__class__.__name__
    if module_name.split('_')[0] == "Function":
        module.b = Parameter(torch.rand(1, 2))

def weight_initialization(module):
    module_name = module.__class__.__name__

    if module_name.split('_')[0] == "Function":
        module.W.data.fill_(1.)
        module.b.data.fill_(1.)

# X @ W + b
def linear_transformation(module):
    def linear_forward(self, x):
        return x @ self.W.T + self.b
    module_name = module.__class__.__name__

    if module_name.split('_')[0] == "Function":
        module.forward = partial(linear_forward, module)

returned_module = model.apply(add_bias)
returned_module = model.apply(weight_initialization)
returned_module = model.apply(linear_transformation)